name: test sftp
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set date
      run: |
        echo "DATE=$(date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
        timedatectl
    - name: Deploy
      run: |
        touch test.txt
        cp test.txt ${{ env.DATE }}.txt
        ls -la
