name: test sftp
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set date
      run: |
        echo "DATE=output-$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
    - name: Deploy
#      env:
#        DATE: $(date "+%Y%m%d-%H%M%S")
      run: |
        touch test.txt
        cp test.txt ${{ env.DATE }}.txt
        cp test.txt $DATE.txt
        echo $DATE
        ls -la
