name: test sftp
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Deploy
#      env:
#        DATE: $(date "+%Y%m%d-%H%M%S")
      run: |
        touch test.txt
        echo "::set-output name=date::$(date '+%Y%m%d-%H%M%S')"
        echo "DATE=output-$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
        cp test.txt new-${{steps.Deploy.outputs.date}}.txt
        cp test.txt new-${{env.DATE}}.txt
        ls -la
